[workspace]
resolver = "3"
members = ["crates/core", "crates/routing", "crates/plan", "crates/wasm"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[workspace.dependencies]
birdseye-core = { path = "crates/core" }
birdseye-routing = { path = "crates/routing" }
birdseye-plan = { path = "crates/plan" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
