[package]
name = "birdseye-plan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
birdseye-core.workspace = true
birdseye-routing.workspace = true
fixedbitset = "0.5.7"
geo = { version = "0.33.1", default-features = false }
rstar = "0.13.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"

[dev-dependencies]
approx = "0.5.1"
